2024-12-01 15:09:59,368 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-12-01 15:09:59,369 [INFO] [33mPress CTRL+C to quit[0m
2024-12-01 15:10:21,006 [ERROR] Error occurred: __init__() missing 1 required positional argument: 'movie'
Traceback (most recent call last):
  File "D:\Udacity\FSND_Capstone\backend\app\__init__.py", line 202, in add_actor
    movie_id = body['movie_id'],
TypeError: __init__() missing 1 required positional argument: 'movie'
2024-12-01 15:10:23,650 [INFO] 127.0.0.1 - - [01/Dec/2024 15:10:23] "[35m[1mPOST /actors HTTP/1.1[0m" 500 -
2024-12-01 15:11:28,456 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-12-01 15:11:28,458 [INFO] [33mPress CTRL+C to quit[0m
2024-12-01 15:11:36,363 [INFO] 127.0.0.1 - - [01/Dec/2024 15:11:36] "[35m[1mPOST /actors HTTP/1.1[0m" 500 -
2024-12-01 15:11:36,385 [ERROR] Error on request:
Traceback (most recent call last):
  File "D:\Udacity\FSND_Capstone\backend\app\__init__.py", line 202, in add_actor
    movie_id = body['movie_id'],
TypeError: __init__() missing 1 required positional argument: 'movie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\werkzeug\serving.py", line 320, in execute
    application_iter = app(environ, start_response)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Udacity\FSND_Capstone\backend\app\auth.py", line 131, in wrapper
    return f(payload,*args, **kwargs)
  File "D:\Udacity\FSND_Capstone\backend\app\__init__.py", line 212, in add_actor
    return jsonify({f"Error occurred: {e}"}), 500
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
2024-12-01 15:11:56,309 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-12-01 15:11:56,311 [INFO] [33mPress CTRL+C to quit[0m
2024-12-01 15:12:05,685 [INFO] 127.0.0.1 - - [01/Dec/2024 15:12:05] "[35m[1mPOST /actors HTTP/1.1[0m" 500 -
2024-12-01 15:12:05,696 [ERROR] Error on request:
Traceback (most recent call last):
  File "D:\Udacity\FSND_Capstone\backend\app\__init__.py", line 202, in add_actor
    movie_id = body['movie_id'],
TypeError: __init__() missing 1 required positional argument: 'movie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\werkzeug\serving.py", line 320, in execute
    application_iter = app(environ, start_response)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Udacity\FSND_Capstone\backend\app\auth.py", line 131, in wrapper
    return f(payload,*args, **kwargs)
  File "D:\Udacity\FSND_Capstone\backend\app\__init__.py", line 212, in add_actor
    return jsonify({f"Error occurred: {e}"})
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "d:\Udacity\FSND_Capstone\backend\.venv\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
2024-12-01 15:13:10,281 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-12-01 15:13:10,282 [INFO] [33mPress CTRL+C to quit[0m
2024-12-01 15:13:15,642 [INFO] 127.0.0.1 - - [01/Dec/2024 15:13:15] "[31m[1mDELETE /movies/1 HTTP/1.1[0m" 405 -
2024-12-01 15:13:34,410 [INFO] 127.0.0.1 - - [01/Dec/2024 15:13:34] "[31m[1mDELETE /movies/1 HTTP/1.1[0m" 405 -
2024-12-01 15:13:51,896 [INFO] 127.0.0.1 - - [01/Dec/2024 15:13:51] "[31m[1mDELETE /movies/1 HTTP/1.1[0m" 405 -
2024-12-01 15:15:27,843 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-12-01 15:15:27,844 [INFO] [33mPress CTRL+C to quit[0m
2024-12-01 15:15:42,884 [INFO] 127.0.0.1 - - [01/Dec/2024 15:15:42] "[31m[1mDELETE /movies/1 HTTP/1.1[0m" 405 -
2024-12-01 15:17:04,741 [WARNING] Unknown option passed to Flask-CORS: allow_methods
2024-12-01 15:17:05,325 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-12-01 15:17:05,326 [INFO] [33mPress CTRL+C to quit[0m
2024-12-01 15:17:13,647 [INFO] 127.0.0.1 - - [01/Dec/2024 15:17:13] "[31m[1mDELETE /movies/1 HTTP/1.1[0m" 405 -
